print("---------Student Management System---------")
print("1. Add Student Details..")
print("2. View Students")
print("3.Search Student")
print("4.Update Marks")
print("5. Delete Student")
print("6. Student Average")
print("Export Report to CSV")
print("Exit")